#!/bin/bash
#Menu Adaptado Completo

#Donwload
wget -O /bin/menu https://raw.githubusercontent.com/plusc1-caua/install/main/Install/Skin_Plus/menuV2/menu > /dev/null 2>&1

#Permisos
chmod +x /bin/menu

#Ejecucion
/bin/menu

#fim