#!/bin/bash
#Menu Original

#Donwload
wget -O /bin/menu https://raw.githubusercontent.com/plusc1-caua/install/main/script/Modulos/menu > /dev/null 2>&1

#Permisos
chmod +x /bin/menu

#Ejecucion
/bin/menu

#fim