#!/bin/bash

## sshd back
cp /etc/ssh/sshd_config /etc/ssh/sshd_back > /dev/null 2>&1

## Acceso Rapido
echo "/bin/menu" > /bin/h && chmod +x /bin/h > /dev/null 2>&1

## Version
rm -rf $HOME/versao*; wget https://raw.githubusercontent.com/plusc1-caua/install/main/script/versao > /dev/null 2>&1

## Reinstalar
echo "apt-get update -y; apt-get upgrade -y; wget https://raw.githubusercontent.com/plusc1-caua/install/main/script/Plus; chmod 777 Plus; ./Plus" > /bin/sshplus && chmod +x /bin/sshplus > /dev/null 2>&1

## Menu
wget -O /bin/menuV1 https://raw.githubusercontent.com/plusc1-caua/install/main/script/Skin_Plus/menuv1/Install > /dev/null 2>&1
chmod +x /bin/menuV1 > /dev/null 2>&1

## Systemverify
rm -rf $HOME/systemverify* > /dev/null 2>&1

#fim